BAU: Add check ignore-scripts is true in GHA
- ignore-scripts (set in .npmrc) should be set to true
- pre- and post- install scripts have been used as an attack vector in
  Sha1-Hulud 2.0 recently, and have been deemed to be unnecessary for
  building One Login projects

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -30,8 +30,16 @@ jobs:
           cache: "npm"
           cache-dependency-path: "package-lock.json"
 
+      - name: Check npm ignore-scripts config
+        run: |
+          if [ "$(npm config get ignore-scripts)" = "false" ]; then
+            echo "Error: ignore-scripts is set to false"
+            exit 1
+          else
+            echo "ignore-scripts is set to true"
+          fi
       - name: Install dependencies
-        run: npm ci
+        run: npm ci --ignore-scripts
 
       - name: Run pre-commit
         uses: whi-tw/pre-commit-action@9a134f4f53ddd4071215facfc20ea754f9cb337b # v3.1.1
diff --git a/.github/workflows/pre-merge-checks.yml b/.github/workflows/pre-merge-checks.yml
--- a/.github/workflows/pre-merge-checks.yml
+++ b/.github/workflows/pre-merge-checks.yml
@@ -30,8 +30,16 @@ jobs:
           node-version: 20.17.0
           cache: "npm"
           cache-dependency-path: "package-lock.json"
+      - name: Check npm ignore-scripts config
+        run: |
+          if [ "$(npm config get ignore-scripts)" = "false" ]; then
+            echo "Error: ignore-scripts is set to false"
+            exit 1
+          else
+            echo "ignore-scripts is set to true"
+          fi
       - name: Install dependencies
-        run: npm ci
+        run: npm ci --ignore-scripts
       - name: Check formatting
         run: npm run check-pretty
       - name: Run lint
